name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_VALID_EMAIL: ${{ secrets.PLAYWRIGHT_VALID_EMAIL }}
          PLAYWRIGHT_VALID_PASSWORD: ${{ secrets.PLAYWRIGHT_VALID_PASSWORD }}
        run: npx playwright test --ui
