name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install libraries for Playwright browsers
        run: sudo apt-get update && sudo apt-get install -y \
              libwoff2dec1 libvpx6 libevent-2.1-7 libopus0 \
              libgstallocators-1.0-0 libgstapp-1.0-0 \
              libgstpbutils-1.0-0 libgstaudio-1.0-0 \
              libgstgl-1.0-0 libgsttag-1.0-0 libgstvideo-1.0-0 \
              libgstcodecparsers-1.0-0 libgstfft-1.0-0 \
              libflite1 libflite-usenglish1 libflite-cmu-grapheme-lang1 \
              libflite-cmu-grapheme-lex1 libflite-cmu-indic-lang1 \
              libflite-cmu-indic-lex1 libflite-cmulex1 libflite-cmu-time-awb1 \
              libflite-cmu-us-awb1 libflite-cmu-us-kal16 libflite-cmu-us-kal \
              libflite-cmu-us-rms libflite-cmu-us-slt libavif13 \
              libharfbuzz-icu0 libhyphen0 libmanette-0.2-0 \
              libgles2 libx264

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_VALID_EMAIL: ${{ secrets.PLAYWRIGHT_VALID_EMAIL }}
          PLAYWRIGHT_VALID_PASSWORD: ${{ secrets.PLAYWRIGHT_VALID_PASSWORD }}
        run: npx playwright test
